### ISSUE TITLE
Bien Gustavo, pero...

### ISSUE THREAD

**Issue by NITDev94** [4GeeksAcademy/GusCastle25-Post-de-Instagram#1]
1. Dale espacio al post dentro del body, que no toque arriba y abajo de la web.
2. el texto y el titulo de la foto están demasiado pegados al borde izq, dale espacio que quede mejor estéticamente.
3. dale un border al post y que quede mas bonito.

**Comment by GusCastle25** [comment]
Buenas noches Noe, creo que ya hice los cambios que me aconsejastes. Por favor avísame si te gusta y te parece bien así o consideras que podría mejorarlo un poco más. Un saludo!!!

![Captura de pantalla 2024-02-25 193422](https://github.com/4GeeksAcademy/GusCastle25-Post-de-Instagram/assets/157417128/4d04578c-0c92-4300-810d-513cf53f2da5)
